/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppKoshaRouteImport } from './routes/_app/kosha'
import { Route as AppDrishtiRouteImport } from './routes/_app/drishti'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChakravyuhaRouteImport } from './routes/_app/chakravyuha'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppKoshaRoute = AppKoshaRouteImport.update({
  id: '/kosha',
  path: '/kosha',
  getParentRoute: () => AppRoute,
} as any)
const AppDrishtiRoute = AppDrishtiRouteImport.update({
  id: '/drishti',
  path: '/drishti',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChakravyuhaRoute = AppChakravyuhaRouteImport.update({
  id: '/chakravyuha',
  path: '/chakravyuha',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chakravyuha': typeof AppChakravyuhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/drishti': typeof AppDrishtiRoute
  '/kosha': typeof AppKoshaRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chakravyuha': typeof AppChakravyuhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/drishti': typeof AppDrishtiRoute
  '/kosha': typeof AppKoshaRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/chakravyuha': typeof AppChakravyuhaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drishti': typeof AppDrishtiRoute
  '/_app/kosha': typeof AppKoshaRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chakravyuha'
    | '/dashboard'
    | '/drishti'
    | '/kosha'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chakravyuha'
    | '/dashboard'
    | '/drishti'
    | '/kosha'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/chakravyuha'
    | '/_app/dashboard'
    | '/_app/drishti'
    | '/_app/kosha'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kosha': {
      id: '/_app/kosha'
      path: '/kosha'
      fullPath: '/kosha'
      preLoaderRoute: typeof AppKoshaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drishti': {
      id: '/_app/drishti'
      path: '/drishti'
      fullPath: '/drishti'
      preLoaderRoute: typeof AppDrishtiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chakravyuha': {
      id: '/_app/chakravyuha'
      path: '/chakravyuha'
      fullPath: '/chakravyuha'
      preLoaderRoute: typeof AppChakravyuhaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChakravyuhaRoute: typeof AppChakravyuhaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDrishtiRoute: typeof AppDrishtiRoute
  AppKoshaRoute: typeof AppKoshaRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChakravyuhaRoute: AppChakravyuhaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDrishtiRoute: AppDrishtiRoute,
  AppKoshaRoute: AppKoshaRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
